_G["SCORE_0"] = 0
_G["SCORE_10"] = 1
_G["SCORE_100"] = 2
_G["SCORE_200"] = 3
_G["SCORE_400"] = 4
_G["SCORE_800"] = 5
_G["SCORE_1000"] = 6
_G["SCORE_2000"] = 7
_G["SCORE_4000"] = 8
_G["SCORE_8000"] = 9
_G["SCORE_1UP"] = 10
_G["SCORE_2UP"] = 11
_G["SCORE_3UP"] = 12
_G["SCORE_5UP"] = 13

-- Alias for HARM_TYPE_OFFSCREEN, as defined in C++
_G["HARM_TYPE_VANISH"] = 9

_G["LEVEL_WIN_TYPE_NONE"] = 0
_G["LEVEL_WIN_TYPE_ROULETTE"] = 1
_G["LEVEL_WIN_TYPE_SMB3ORB"] = 2
_G["LEVEL_WIN_TYPE_OFFSCREEN"] = 3
_G["LEVEL_WIN_TYPE_KEYHOLE"] = 4
_G["LEVEL_WIN_TYPE_SMB2ORB"] = 5
_G["LEVEL_WIN_TYPE_WARP"] = 6
_G["LEVEL_WIN_TYPE_STAR"] = 7
_G["LEVEL_WIN_TYPE_TAPE"] = 8

_G["LEVEL_END_STATE_ROULETTE"] = 1
_G["LEVEL_END_STATE_SMB3ORB"] = 2
_G["LEVEL_END_STATE_KEYHOLE"] = 3
_G["LEVEL_END_STATE_SMB2ORB"] = 4
_G["LEVEL_END_STATE_GAMEEND"] = 5
_G["LEVEL_END_STATE_STAR"] = 6
_G["LEVEL_END_STATE_TAPE"] = 7

_G["LEVEL_TIMER_RESULT_KILL"] = 0
_G["LEVEL_TIMER_RESULT_EVENT"] = 1

_G["POWERUP_SMALL"] = 1
_G["PLAYER_BIG"] = 2
_G["PLAYER_FIREFLOWER"] = 3
_G["PLAYER_LEAF"] = 4
_G["POWERUP_TANOOKIE"] = 5
_G["PLAYER_HAMMER"] = 6
_G["PLAYER_ICE"] = 7
_G["PLAYER_BUBBLE"] = 8

-- Alias for POWERUP_TANOOKIE, as defined in C++
_G["POWERUP_TANOOKI"] = 5

_G["MOUNT_NONE"] = 0
_G["MOUNT_BOOT"] = 1
_G["MOUNT_CLOWNCAR"] = 2
_G["MOUNT_YOSHI"] = 3

_G["BOOTCOLOR_GREEN"] = 1
_G["BOOTCOLOR_RED"] = 2
_G["BOOTCOLOR_BLUE"] = 3

_G["YOSHICOLOR_GREEN"] = 1
_G["YOSHICOLOR_BLUE"] = 2
_G["YOSHICOLOR_YELLOW"] = 3
_G["YOSHICOLOR_RED"] = 4
_G["YOSHICOLOR_BLACK"] = 5
_G["YOSHICOLOR_PURPLE"] = 6
_G["YOSHICOLOR_PINK"] = 7
_G["YOSHICOLOR_CYAN"] = 8

_G["FORCEDSTATE_NONE"] = 0
_G["FORCEDSTATE_POWERUP_BIG"] = 1
_G["FORCEDSTATE_POWERDOWN_SMALL"] = 2
_G["FORCEDSTATE_PIPE"] = 3
_G["FORCEDSTATE_POWERUP_FIRE"] = 4
_G["FORCEDSTATE_POWERUP_LEAF"] = 5
_G["FORCEDSTATE_RESPAWN"] = 6
_G["FORCEDSTATE_DOOR"] = 7
_G["FORCEDSTATE_INVISIBLE"] = 8
_G["FORCEDSTATE_ONTONGUE"] = 9
_G["FORCEDSTATE_SWALLOWED"] = 10
_G["FORCEDSTATE_POWERUP_TANOOKI"] = 11
_G["FORCEDSTATE_POWERUP_HAMMER"] = 12
_G["FORCEDSTATE_POWERUP_ICE"] = 41
_G["FORCEDSTATE_POWERUP_BUBBLE"] = 42
_G["FORCEDSTATE_POWERDOWN_FIRE"] = 227
_G["FORCEDSTATE_POWERDOWN_ICE"] = 228
_G["FORCEDSTATE_MEGASHROOM"] = 499
_G["FORCEDSTATE_TANOOKI_POOF"] = 500
_G["FORCEDSTATE_POWERDOWN_NORMAL"] = 551

_G["VK_A"] = 4
_G["VK_B"] = 5
_G["VK_C"] = 6
_G["VK_D"] = 7
_G["VK_E"] = 8
_G["VK_F"] = 9
_G["VK_G"] = 10
_G["VK_H"] = 11
_G["VK_I"] = 12
_G["VK_J"] = 13
_G["VK_K"] = 14
_G["VK_L"] = 15
_G["VK_M"] = 16
_G["VK_N"] = 17
_G["VK_O"] = 18
_G["VK_P"] = 19
_G["VK_Q"] = 20
_G["VK_R"] = 21
_G["VK_S"] = 22
_G["VK_T"] = 23
_G["VK_U"] = 24
_G["VK_V"] = 25
_G["VK_W"] = 26
_G["VK_X"] = 27
_G["VK_Y"] = 28
_G["VK_Z"] = 29
_G["VK_1"] = 30
_G["VK_2"] = 31
_G["VK_3"] = 32
_G["VK_4"] = 33
_G["VK_5"] = 34
_G["VK_6"] = 35
_G["VK_7"] = 36
_G["VK_8"] = 37
_G["VK_9"] = 38
_G["VK_0"] = 39
_G["VK_RETURN"] = 40
_G["VK_ESCAPE"] = 41
_G["VK_BACK"] = 42
_G["VK_TAB"] = 43
_G["VK_SPACE"] = 44

_G["VK_CAPITAL"] = 57
_G["VK_F1"] = 58
_G["VK_F2"] = 59
_G["VK_F3"] = 60
_G["VK_F4"] = 61
_G["VK_F5"] = 62
_G["VK_F6"] = 63
_G["VK_F7"] = 64
_G["VK_F8"] = 65
_G["VK_F9"] = 66
_G["VK_F10"] = 67
_G["VK_F11"] = 68
_G["VK_F12"] = 69

_G["VK_HOME"] = 74
_G["VK_PRIOR"] = 75
_G["VK_DELETE"] = 76
_G["VK_END"] = 77
_G["VK_NEXT"] = 78
_G["VK_RIGHT"] = 79
_G["VK_LEFT"] = 80
_G["VK_DOWN"] = 81
_G["VK_UP"] = 82

_G["VK_CONTROL"] = 224
_G["VK_LCONTROL"] = 224
_G["VK_SHIFT"] = 225
_G["VK_LSHIFT"] = 225
_G["VK_ALT"] = 226
_G["VK_LALT"] = 226
_G["VK_WINDOWS"] = 227
_G["VK_RCONTROL"] = 228
_G["VK_RSHIFT"] = 229
_G["VK_RALT"] = 230

_G["FIELD_BYTE"] = 1
_G["FIELD_WORD"] = 2
_G["FIELD_DWORD"] = 3
_G["FIELD_FLOAT"] = 4
_G["FIELD_DFLOAT"] = 5

_G["FIELD_STRING"] = 6
_G["FIELD_BOOL"] = 7

return {}